name: Build

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]


env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'ref/tags/v')

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Install cross for cross-compilation
        run: cargo install cross

      - name: Build Windows executable
        run: cross build --target x86_64-pc-windows-gnu --release

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes \
              target/x86_64-pc-windows-gnu/release/cmt.exe
    
